from agent.settings import load_settings

_CFG = load_settings()

MODEL = _CFG["MODEL"]
EMBED_MODEL = _CFG["EMBED_MODEL"]

PROJECT_ROOT = _CFG["PROJECT_ROOT"]
MAX_FILE_SIZE = _CFG["MAX_FILE_SIZE"]

OLLAMA_BASE_URL = _CFG["OLLAMA_BASE_URL"]
OLLAMA_URL = _CFG["OLLAMA_URL"]
OLLAMA_EMBED_URL = _CFG["OLLAMA_EMBED_URL"]

REQUEST_TIMEOUT = _CFG["REQUEST_TIMEOUT"]
TOP_K_RESULTS = _CFG["TOP_K_RESULTS"]
AUTO_MAX_STEPS = _CFG["AUTO_MAX_STEPS"]
AUTO_TEST_COMMAND = _CFG["AUTO_TEST_COMMAND"]
DRY_RUN = _CFG["DRY_RUN"]
MAX_RETRIES_JSON = _CFG["MAX_RETRIES_JSON"]

CHAT_HISTORY_PATH = _CFG["CHAT_HISTORY_PATH"]
EVENT_LOG_PATH = _CFG["EVENT_LOG_PATH"]

MEMORY_INDEX_DIR = _CFG["MEMORY_INDEX_DIR"]
CHUNK_SIZE = _CFG["CHUNK_SIZE"]
CHUNK_OVERLAP = _CFG["CHUNK_OVERLAP"]
MAX_CHUNKS_PER_FILE = _CFG["MAX_CHUNKS_PER_FILE"]
CONTEXT_BUDGET_CHARS = _CFG["CONTEXT_BUDGET_CHARS"]
CONTEXT_MAX_CHUNKS = _CFG["CONTEXT_MAX_CHUNKS"]
CONTEXT_MAX_PER_FILE = _CFG["CONTEXT_MAX_PER_FILE"]
MEMORY_QUERY_CACHE_SIZE = _CFG["MEMORY_QUERY_CACHE_SIZE"]

FORMAT_COMMAND = _CFG["FORMAT_COMMAND"]
LINT_COMMAND = _CFG["LINT_COMMAND"]
TEST_COMMAND = _CFG["TEST_COMMAND"]
OPENAI_API_KEY = _CFG["OPENAI_API_KEY"]
